
import { Product, ProductCategory } from './types';

const GENERIC_PIZZA_IMAGE = 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=400&auto=format&fit=crop';
const GENERIC_DRINK_IMAGE = 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400&auto=format&fit=crop';
const GENERIC_SWEET_PIZZA_IMAGE = 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=400&auto=format&fit=crop';

export const MENU_ITEMS: Product[] = [
  // Pizzas Salgadas (1-67)
  { id: '1', name: 'ALHO', description: 'Mussarela e alho frito', price: 43.00, priceSmall: 31.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '2', name: 'AMERICANA', description: 'Presunto, mussarela, ovo e bacon', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '3', name: 'AUSTRIACA', description: 'Mussarela e peito de peru', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '4', name: 'ATUM', description: 'Atum em pedaços e cebola', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '5', name: 'ATUM 2', description: 'Atum em pedaços, cebola e catupiry', price: 52.00, priceSmall: 40.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '6', name: 'ATUM 3', description: 'Atum em pedaços e mussarela', price: 55.00, priceSmall: 43.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '7', name: 'ATUM ESPECIAL', description: 'Atum em pedaços, cebola, mussarela e catupiry', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '8', name: 'BACON', description: 'Bacon e mussarela', price: 45.00, priceSmall: 33.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '9', name: 'BAIANA', description: 'Calabresa, ovo, cebola e pimenta calabresa', price: 45.00, priceSmall: 33.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '10', name: 'BAIANA 2', description: 'Calabresa, ovo, cebola, mussarela, pimenta calabresa, pimenta biquinho', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '11', name: 'BAURU', description: 'Presunto, mussarela e tomate', price: 43.00, priceSmall: 31.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '12', name: 'BERTIOGA', description: 'Calabresa, ovo, bacon e catupiry', price: 45.00, priceSmall: 33.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '13', name: 'BURGUESA', description: 'Presunto, ovo, milho, palmito e mussarela', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '14', name: 'BRÓCOLIS', description: 'Brócolis, mussarela e alho frito', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '15', name: 'BRÓCOLIS ESPECIAL', description: 'Brócolis, mussarela, bacon, alho frito e batata palha', price: 52.00, priceSmall: 40.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '16', name: 'BRASILEIRINHO', description: 'Calabresa, cebola, mussarela, tomate e provolone', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '17', name: 'CALABRESA', description: 'Calabresa e cebola', price: 40.00, priceSmall: 28.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '18', name: 'CALAMUSSA', description: 'Mussarela e calabresa por cima', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '19', name: 'CALAMUSSA ESPECIAL', description: 'Mussarela, calabresa e cream cheese', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '20', name: 'CALAMITO', description: 'Calabresa, cebola, palmito e mussarela', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '21', name: 'CALABRESA SUPREMA', description: 'Mussarela, calabresa, cebola e cream cheese', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '22', name: 'CALACATU ESPECIAL', description: 'Calabresa, cebola, mussarela e catupiry', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '23', name: 'CALALOUKA', description: 'Calabresa, mussarela e batata palha', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '24', name: 'CINCO QUEIJOS', description: 'Mussarela, catupiry, cheddar, parmesão e provolone', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '25', name: 'CROCANTE', description: 'Mussarela, cheddar e batata palha', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '26', name: 'CROCANTE 2', description: 'Mussarela, catupiry e batata palha', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '27', name: 'CAIPIRA', description: 'Frango desfiado, ovo, milho e cheddar', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '28', name: 'CAIPIRA 2', description: 'Frango desfiado, ovo, milho e catupiry', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '29', name: 'COLISEU', description: 'Mussarela, peito de peru, milho e palmito', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '30', name: 'CORINTHIANA', description: 'Mussarela, frango, cebola, pimentão, ovo e bacon', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '31', name: 'CAIÇARA', description: 'Mussarela, bacon e alho frito', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '32', name: 'DOIS QUEIJOS', description: 'Mussarela e catupiry', price: 45.00, priceSmall: 32.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '33', name: "DU' CHEFE", description: 'Peito de peru, mussarela, bacon, cheddar e alho', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '34', name: 'ESCAROLA', description: 'Mussarela, escarola, bacon e alho frito', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '35', name: 'FLORENTINA', description: 'Brócolis, mussarela, parmesão e tomate cereja', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '36', name: 'FLORENTINA 2', description: 'Brócolis, mussarela, provolone e tomate cereja', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '37', name: 'FRANCESA', description: 'Presunto, mussarela, ovo, pimentão e catupiry', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '38', name: 'FRANGO COM CATUPIRY', description: 'Frango desfiado e catupiry', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '39', name: 'FRANGO ESPECIAL', description: 'Frango desfiado, mussarela e catupiry', price: 50.00, priceSmall: 38.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '40', name: 'FRANBACON', description: 'Frango desfiado, mussarela, catupiry e bacon', price: 52.00, priceSmall: 40.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '41', name: 'LITORAL', description: 'Calabresa, cebola e cheddar', price: 45.00, priceSmall: 33.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '42', name: 'LITORAL 2', description: 'Calabresa, cebola e catupiry', price: 45.00, priceSmall: 33.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '43', name: 'JANGADA', description: 'Presunto, mussarela, milho e bacon', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '44', name: 'JARDINEIRA', description: 'Escarola, brócolis, ervilha e mussarela', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '45', name: 'MILHO', description: 'Milho e mussarela', price: 45.00, priceSmall: 33.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '46', name: 'MAMMA MIA', description: 'Mussarela, calabresa, provolone, bacon e tomate cereja', price: 57.00, priceSmall: 45.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '47', name: 'MARGUERITA', description: 'Mussarela, parmesão, manjericão e tomate', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '48', name: 'MEXICANA', description: 'Calabresa, mussarela, manjericão e pimenta calabresa', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '49', name: 'MUSSARELA', description: 'Mussarela e tomate', price: 40.00, priceSmall: 28.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '50', name: 'MODA RAIZ', description: 'Presunto, milho, palmito, cebola, calabresa, mussarela, tomate, bacon e catupiry', price: 65.00, priceSmall: 53.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '51', name: 'MODA DA CASA', description: 'Frango, mussarela, milho, bacon e cream cheese', price: 52.00, priceSmall: 40.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '52', name: 'NONNA', description: 'Mussarela, ovo, bacon, tomate, finalizando com parmesão ralado', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '53', name: 'NAPOLITANA', description: 'Mussarela, parmesão e tomate', price: 48.00, priceSmall: 36.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '54', name: 'PERUIBÃO', description: 'Atum em pedaços, palmito, cebola e catupiry', price: 52.00, priceSmall: 40.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '55', name: 'PALMEIRENSE', description: 'Lombo, mussarela, bacon, parmesão e manjericão', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '56', name: 'PORTUGUESA', description: 'Presunto, mussarela, cebola, palmito, ervilha e ovo', price: 52.00, priceSmall: 40.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '57', name: 'PALMITO', description: 'Palmito e mussarela', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '58', name: 'ROMAR', description: 'Presunto, mussarela, catupiry e tomate', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '59', name: 'RIBAMAR', description: 'Calabresa, mussarela, ervilha, ovo e cebola', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '60', name: 'SANTISTA', description: 'Atum, cebola, palmito, mussarela e tomate cereja', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '61', name: 'SÃO PAULINA', description: 'Frango desfiado, mussarela, bacon e batata palha', price: 60.00, priceSmall: 48.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '62', name: 'TRÊS QUEIJOS', description: 'Mussarela, catupiry e parmesão', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '63', name: 'TOSCANA', description: 'Calabresa e mussarela', price: 43.00, priceSmall: 31.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '64', name: 'TOSCANA ESPECIAL', description: 'Calabresa, cebola e mussarela', price: 45.00, priceSmall: 33.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '65', name: 'QUATRO QUEIJO', description: 'Mussarela, catupiry, parmesão e provolone', price: 55.00, priceSmall: 43.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '66', name: 'VEGETARIANA', description: 'Escarola, brócolis, milho, ervilha, mussarela e tomate cereja', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },
  { id: '67', name: 'ZATTERA', description: 'Brócolis, lombo, mussarela e tomate', price: 47.00, priceSmall: 35.00, category: ProductCategory.PIZZA, image: GENERIC_PIZZA_IMAGE, allowSize: true },

  // Pizzas Doces (68-75)
  { id: '68', name: 'ROMEU E JULIETA', description: 'Mussarela e goiabada', price: 45.00, priceSmall: 33.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },
  { id: '69', name: 'BRIGADEIRO', description: 'Cobertura de chocolate ao leite Nestlé e granulado', price: 60.00, priceSmall: 48.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },
  { id: '70', name: 'SONHO DE VALSA', description: 'Cobertura de chocolate ao leite Nestlé e bombom Sonho de Valsa', price: 60.00, priceSmall: 48.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },
  { id: '71', name: 'OURO BRANCO', description: 'Cobertura de chocolate ao leite Nestlé e bombom Ouro Branco', price: 60.00, priceSmall: 48.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },
  { id: '72', name: 'CONFETE', description: 'Cobertura de chocolate ao leite Nestlé e confete', price: 60.00, priceSmall: 48.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },
  { id: '73', name: 'PRESTIGIO', description: 'Cobertura de chocolate ao leite Nestlé, coco ralado e pedaços de chocolate Prestígio', price: 60.00, priceSmall: 48.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },
  { id: '74', name: 'KIT-KAT', description: 'Cobertura de chocolate ao leite Nestlé, com chocolate de Kit-Kat em pedaços', price: 60.00, priceSmall: 48.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },
  { id: '75', name: 'NEGRESCO', description: 'Cobertura de chocolate ao leite Nestlé, com biscoito Negresco em pedaços', price: 60.00, priceSmall: 48.00, category: ProductCategory.SWEET_PIZZA, image: GENERIC_SWEET_PIZZA_IMAGE, allowSize: true },

  // Bebidas
  { id: 'd1', name: 'Coca-Cola Lata', description: '350ml', price: 6.00, category: ProductCategory.DRINK, image: GENERIC_DRINK_IMAGE, allowSize: false },
  { id: 'd2', name: 'Guaraná Antarctica', description: '350ml', price: 6.00, category: ProductCategory.DRINK, image: GENERIC_DRINK_IMAGE, allowSize: false },
  { id: 'd3', name: 'Coca-Cola 2L', description: 'Garrafa Pet', price: 14.00, category: ProductCategory.DRINK, image: GENERIC_DRINK_IMAGE, allowSize: false },
];
